dataset_name: StudentPerformance
bootstrap_fraction: 0.8
n_estimators: 10
#computation_mode: error_analysis
num_runs: 1
runs_seed_lst: [100]
#sensitive_attributes_dct: {'sex': 'F'}
sensitive_attributes_dct: {'SEX': '2', 'RAC1P': ['2', '3', '4', '5', '6', '7', '8', '9'], 'SEX & RAC1P': None}