dataset_name: Folktables_NY_2018_Employment
bootstrap_fraction: 0.8
n_estimators: 200
computation_mode: error_analysis
num_runs: 1
sensitive_attributes_dct: {'SEX': '0', 'RAC1P': '0', 'SEX & RAC1P': None}